name: Import Smoke
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Import check
        run: |
          python - <<'PY'
          try:
              import risk_manager_v2
              from risk_manager_v2.core.clients.projectx import ProjectXClient
              from risk_manager_v2.core.config import ConfigStore
              from risk_manager_v2.core.auth import AuthManager
              print("✅ imports ok")
          except Exception as e:
              raise SystemExit(e)
          PY
