name: Import Smoke
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Import check
        run: |
          python - <<'PY'
          import sys, traceback
          print("python:", sys.version)
          try:
              # minimal imports that must always work
              import risk_manager_v2
              from risk_manager_v2.core.config import ConfigStore
              from risk_manager_v2.core.auth import AuthManager
              print("imports ok")
          except Exception:
              traceback.print_exc()
              raise SystemExit(1)
          PY
