name: smoke
on:
  pull_request:
  push:
    branches: [ main, feat/**, chore/**, fix/** ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Selftests
        run: |
          python -m risk_manager_v2.cli.policy selftest
          python -m risk_manager_v2.cli.monitoring tick
